### ISSUE TITLE
Release l337 and l337-postgres on crates.io

### ISSUE THREAD

**Issue by bikeshedder** [OneSignal/L3-37#30]
I'm using `l337` and `l337-postgres` in my current project using the following lines in my `Cargo.toml`:

```toml
[dependencies.l337]
git = "https://github.com/OneSignal/L3-37"
rev = "6d96fefa75c748d4ac3618ab2bd9523d589b6cd2"

[dependencies.l337-postgres]
git = "https://github.com/OneSignal/L3-37"
rev = "6d96fefa75c748d4ac3618ab2bd9523d589b6cd2"
```

Are there any plans on releasing `l337` and `l337-postgres` to `crates.io` in the near future?
